- project:
    templates:
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python3-victoria-jobs
      - check-requirements
      - release-notes-jobs-python3
      - publish-openstack-docs-pti
      - openstackclient-plugin-jobs
    check:
      jobs:
        - muranoclient-functional-test-mysql-backend
    gate:
      jobs:
        - muranoclient-functional-test-mysql-backend

- job:
    name: muranoclient-functional-test-mysql-backend
    parent: legacy-dsvm-base
    run: playbooks/legacy/muranoclient-functional-test-mysql-backend/run.yaml
    post-run: playbooks/legacy/muranoclient-functional-test-mysql-backend/post.yaml
    timeout: 4200
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^setup.cfg$
      - ^doc/.*$
      - ^.*\.rst$
      - ^releasenotes/.*$
      - ^muranoclient/tests/.*$
    required-projects:
      - openstack/devstack-gate
      - openstack/heat
      - openstack/murano
      - openstack/murano-dashboard
      - openstack/python-heatclient
      - openstack/python-muranoclient
