- project:
    templates:
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python3-xena-jobs
      - check-requirements
      - release-notes-jobs-python3
      - publish-openstack-docs-pti
      - openstackclient-plugin-jobs
    check:
      jobs:
        - muranoclient-functional-test-mysql-backend
    gate:
      jobs:
        - muranoclient-functional-test-mysql-backend

- job:
    name: muranoclient-functional-test-mysql-backend
    parent: devstack-tox-functional
    timeout: 4200
    vars:
      openrc_enable_export: true
      devstack_plugins:
        heat: https://opendev.org/openstack/heat
        murano: https://opendev.org/openstack/murano
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^setup.cfg$
      - ^doc/.*$
      - ^.*\.rst$
      - ^releasenotes/.*$
      - ^muranoclient/tests/.*$
    required-projects:
      - openstack/heat
      - openstack/murano
      - openstack/murano-dashboard
      - openstack/python-heatclient
      - openstack/python-muranoclient
